join:
  register: '{RED}Nu sunteti inregistrat.{NEWLINE}{RED}Va rugam inregistrati-va cu
    comanda /register <password>.'
  login: '{RED}Va rugam sa va autentificati cu comanda /login <password>.'
  resume: '{BRIGHTGREEN}Bun venit din nou, sesiunea de autentificare a fost reluata.'
  error:
    lockout: Sunteti blocat temporar din cauza ca ati introdus de mai multe ori parola gresit.
    name: Numele jucatorului contine caractere nepermise.
    online: Suneti deja autentificat!
register:
  usage: '{RED}Utilizare corecta: /register <password>'
  success: '{BRIGHTGREEN}V-ati inregistrat cu succes!{NEWLINE}{BRIGHTGREEN}Acum puteti
    sa va autentificati cu comanda /login <password>'
  error:
    disabled: '{RED}Inregistrarea este blocata la moment!'
    registered: '{RED}Sunteti deja inregistrat!'
    limit: '{RED}Nu mai puteti inregitra mai multe conturi!'
    password: '{RED}Parola trebuie sa contina minim {PWMINLENGTH} caractere!'
    email: '{RED}Va rugam folositi o adresa de email valida cind va inregistrati!'
    general: '{RED}Ceva nu a mers cum trebuie!'
login:
  usage: '{RED}Utilizare corecta: /login <password>'
  success: '{BRIGHTGREEN}V-ati autentificat cu succes!'
  error:
    registered: '{RED}Nu sunteti inregistrat!'
    authenticated: '{RED}Sunteti deja autentificat!'
    password: '{RED}Parola gresita!'
    active: '{RED}Contul dvs. nu este activat!'
    general: '{RED}Ceva nu a mers cum trebuie!'
logout:
  success: '{BRIGHTGREEN}Ati iesit din cont!'
  error:
    logged: '{RED}Nu sunteti autentificat!'
    general: '{RED}Ceva nu a mers cum trebuie!'
quit:
  success: '{BRIGHTGREEN}Clientul a inchis conexiunea.'
  error:
    logged: '{RED}Nu sunteti autentificat!'
    general: '{RED}Ceva nu a mers cum trebuie!'
changepw:
  usage: '{RED}Utilizare corecta: /changepw <parola veche> <parola noua>'
  success: '{BRIGHTGREEN}Parola a fost schimbata!'
  error:
    disabled: '{RED}Modificarea parolei este dezactivata la moment.'
    logged: '{RED}Nu sunteti autentificat!'
    incorrect: '{RED}Parola veche incorecta!'
    invalid: '{RED}Parola noua nu satisface regulile de complexitate!'
    general: '{RED}Ceva nu a mers cum trebuie!'
authurl:
  registration: '{RED}AuthURL registration is disabled.'
  changepw: '{RED}AuthURL does not support password changes.'
misc:
  illegal: '{GRAY}Trebuie sa fiti autentificat ca sa puteti face asta!'
  timeout: Autentificarea a durat prea mult timp!
  strikeout: Ati introdus de prea multe ori parola gresita!
  reloaded: '{RED}Serverul a fost reincarcat, trebuie sa va autentificati din nou.'
admin:
  permission: Nu aveti permisiunea pentru utilizarea acestei comenzi!
  debug: Debugging level set to %s
  register:
    usage: '{RED}Correct Usage: /xauth register <player> <password> [email]'
    success: '{BRIGHTGREEN}Account successfully created for: {WHITE}{TARGET}'
    error:
      registered: '{RED}This player is already registered!'
      general: '{RED}Something went wrong while creating an account for {TARGET}'
  changepw:
    usage: '{RED}Correct Usage: /xauth changepw <player> <new password>'
    success: '{TARGET}''s {BRIGHTGREEN}password has been changed!'
    error:
      registered: '{RED}This player is not registered!'
      general: '{RED}Something went wrong while changing {TARGET}''s password!'
  logout:
    usage: '{RED}Correct Usage: /xauth logout <player>'
    error:
      logged: '{TARGET} {RED}is not logged in!'
      general: '{RED}Something went wrong while logging this player out!'
    success:
      player: '{TARGET} {BRIGHTGREEN}has been logged out!'
      target: '{BRIGHTGREEN}You have been logged out by an Administrator!'
  unregister:
    usage: '{RED}Correct Usage: /xauth unregister <player>'
    error:
      registered: '{RED}This player is not registered!'
      general: '{RED}Something went wrong while unregistering this player!'
    success:
      player: '{TARGET} {BRIGHTGREEN}has been unregistered!'
      target: '{RED}You have been unregistered and logged out!'
  location:
    usage: '{RED}Correct Usage: /xauth location set|remove [global]'
    set:
      error:
        global: '{RED}Global teleport location is set to this world.{NEWLINE}{RED}Please
          remove it first.'
        general: '{RED}Something went wrong while setting this location!'
      success:
        regular: '{BRIGHTGREEN}Teleport location for this world set to your location!'
        global: '{BRIGHTGREEN}Global teleport location set to your location!'
    remove:
      error:
        noglobal: '{RED}A global teleport location is not set!'
        notset: '{RED}This world does not have a teleport location!'
        global: '{RED}Global teleport location is set to this world.{NEWLINE}{RED}Please
          use /xauth location remove global'
        general: '{RED}Something went wrong while removing this location!'
      success:
        regular: '{BRIGHTGREEN}Teleport location for this world has been removed!'
        global: '{BRIGHTGREEN}Global teleport location has been removed!'
  reload: '{BRIGHTGREEN}xAuth reloaded.'
  activate:
    usage: '{RED}Correct Usage: /xauth activate <player>'
    error:
      registered: '{RED}This player is not registered!'
      registeredM: '{RED}{TARGET} aren''t registered!'
      active: '{RED}This player is already active!'
      activeM: '{RED}The accounts for {TARGET} are already active!'
      general: '{RED}Something went wrong while activating this player!'
      generalM: '{RED}Something went wrong while activating the accounts!'
    success: '{BRIGHTGREEN}{TARGET} has been activated!'
    successM: '{BRIGHTGREEN}{TARGET} accounts have been activated!'
  profile:
    usage: '{RED}Correct Usage: /xauth profile [player]'
    error:
      registered: '{RED}This player is not registered!'
      console: '{RED}Invalid argument count.'
      general: '{RED}Something went wrong while executing this command!'
    success: '{BRIGHTGREEN}{TARGET}''s profile!'
  lock:
    usage: '{RED}Correct Usage: /xauth lock <player>'
    error:
      registered: '{RED}This player is not registered!'
      registeredM: '{RED}The players {TARGET} aren''t registered!'
      locked: '{RED}This player is already locked!'
      lockedM: '{RED}The accounts for {TARGET} are already locked!'
      general: '{RED}Something went wrong while locking this player!'
      generalM: '{RED}Something went wrong while locking the accounts!'
    success: '{BRIGHTGREEN}{TARGET} has been locked!'
    successM: '{BRIGHTGREEN}{TARGET} accounts have been locked!'
  count:
    usage: '{RED}Correct Usage: /xauth count <all|active|locked>'
    error:
      general: '{RED}Something went wrong while counting the accounts!'
    successAll: '{BRIGHTGREEN}{TARGET} accounts are currently registered'
    successA: '{BRIGHTGREEN}{TARGET} accounts are currently active'
    successL: '{BRIGHTGREEN}{TARGET} accounts are currently locked'
  config:
    usage: '{RED}Correct Usage: /xauth config <node> <value>'
    error:
      exist: '{RED}This configuration node does not exist!'
      int: '{RED}This configuration node requires an integer value!'
      invalid: '{RED}This setting cannot be altered using this command!'
    success: '{BRIGHTGREEN}Configuration updated!'
    value: '{BRIGHTGREEN}%s: {WHITE}%s'
version:
  current-version: '{BRIGHTGREEN}xAuth version: %s'
  update-available: '{BRIGHTGREEN}New version %s available. Check your server.log
    for download instructions.'
  no-update-needed: '{BRIGHTGREEN}Latest xAuth version %s is installed. No update
    needed.'
  success: '{BRIGHTGREEN}Latest xAuth version is %s'
